services:
  inventory-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=InventoryDb;Username=postgres;Password=password
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: InventoryDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_clean:/var/lib/postgresql/data

volumes:
  postgres_data_clean:
